final products = [
  {
    "id": 0,
    "title": "Nike AIR Jordan Black",
    "price": 10000.00,
    "imageUrl": "assets/images/shoes_4.png",
    "company": "Nike",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 1,
    "title": "Zara LaceUp Boots",
    "price": 6000.00,
    "imageUrl": "assets/images/shoes_1.png",
    "company": "Zara",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 2,
    "title": "Zara Low Top Hip-Hop Shoes",
    "price": 7000.00,
    "imageUrl": "assets/images/shoes_2.png",
    "company": "Zara",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 3,
    "title": "Zara Low Top Black",
    "price": 4000.00,
    "imageUrl": "assets/images/shoes_3.png",
    "company": "Zara",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 4,
    "title": "Nike AIR Red",
    "price": 8000.00,
    "imageUrl": "assets/images/shoes_5.png",
    "company": "Nike",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 5,
    "title": "Nike Satrn Motorsports",
    "price": 13000.00,
    "imageUrl": "assets/images/shoes_6.png",
    "company": "Nike",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
  {
    "id": 6,
    "title": "Puma Motorsports Sneakers Ferrari",
    "price": 6000.00,
    "imageUrl": "assets/images/shoes_7.png",
    "company": "Puma",
    "sizes": [6, 7, 8, 9, 10, 11],
  },
];
